import { types } from "util";
import {
  BookUser,
  Calendar,
  Camera,
  Globe,
  Hash,
  Home,
  IdCard,
  Landmark,
  Map,
  MapPin,
  Phone,
  ShieldCheck,
  Sun,
  Transgender,
  TreePine,
  User,
  Users,
} from "lucide-react";
export type newCreationType = "Farmer" | "Crop";
import { ActivityConfig } from "../crops/[id]/utils/cropActions";
export const newCreationForms: Record<newCreationType, ActivityConfig> = {
  Farmer: {
    heading: "Add New Farmer",
    inputs: [
      {
        sub: "Farmer Name",
        name: "farmerName",
        type: "text",
        placeholder: "Enter Farmer Name",
        icons: <User size={13} />,
      },
      {
        sub: "Farmer Image",
        name: "farmerPic",
        type: "url",
        placeholder: "Enter Farmer Image",
        icons: <Camera size={13} />,
      },
      {
        sub: "Farmer Father",
        name: "farmerFather",
        type: "text",
        placeholder: "Enter Farmer Father Name",
        icons: <User size={13} />,
      },
      {
        sub: "Farmer Age",
        name: "farmerAge",
        type: "number",
        placeholder: "Enter Farmer Age",
        icons: <Calendar size={13} />,
      },
      {
        sub: "Gender",
        name: "gender",
        type: "dropDown",
        types: ["Male", "Female"],
        placeholder: "Enter Select Gender",
        icons: <Transgender size={13} />,
      },
      {
        sub: "Mobile",
        name: "phone",
        type: "text",
        placeholder: "Enter Phone Number",
        icons: <Phone size={13} />,
      },
      {
        sub: "Farmer Code",
        name: "farmCode",
        type: "number",
        placeholder: "Enter Farm Code",
        icons: <Hash size={13} />,
      },
      {
        sub: "Country",
        name: "country",
        type: "text",
        placeholder: "Enter Country Name",
        icons: <Globe size={13} />,
      },
      {
        sub: "State",
        name: "state",
        type: "text",
        placeholder: "Enter State",
        icons: <Map size={13} />,
      },
      {
        sub: "District",
        name: "district",
        type: "text",
        placeholder: "Enter District",
        icons: <Landmark size={13} />,
      },
      {
        sub: "Tehsil/Mandal",
        name: "tehsil",
        type: "dropDown",
        types: ["Tehsil", "Mandal"],
        placeholder: "Tehsil/Mandal",
        icons: <MapPin size={13} />,
      },
      {
        sub: "Village",
        name: "village",
        type: "text",
        placeholder: "Enter Village Name",
        icons: <Home size={13} />,
      },
      {
        sub: "Season",
        name: "season",
        type: "text",
        placeholder: "Enter Season",
        icons: <Sun size={13} />,
      },
      {
        sub: "Aadhar Number",
        name: "aadharNumber",
        type: "text",
        placeholder: "Enter Aadhar Number",
        icons: <IdCard size={13} />,
      },
      {
        sub: "Farmer Address",
        name: "address",
        type: "text",
        placeholder: "Enter Address",
        icons: <BookUser size={13} />,
      },
      {
        sub: "Migrant or Local",
        name: "migrantStatus",
        type: "dropDown",
        types: ["Migrant", "Local"],
        placeholder: "Select Status",
        icons: <ShieldCheck size={13} />,
      },
      {
        sub: "Land Holding Area - Own/Lease",
        name: "landHoldingType",
        type: "dropDown",
        types: ["Own", "Lease"],
        placeholder: "Select Land Holding Type",
        icons: <TreePine size={13} />,
      },
      {
        sub: "Farmer Association",
        name: "farmerAssociation",
        type: "text",
        placeholder: "Enter Farmer Association Name",
        icons: <Users size={13} />,
      },
    ],
  },
  Crop: {
    heading: "Add New Crop",
    inputs: [
      {
        sub: "New Crop Name",
        name: "cropName",
        type: "text",
        placeholder: "Crop Name",
      },
      {
        sub: "Crop Image",
        name: "cropImage",
        type: "url",
        placeholder: "Enter Crop Image",
      },
      {
        sub: "Crop Color",
        name: "cropColor",
        type: "color",
        placeholder: "Enter Crop ",
      },
    ],
  },
};
